# -*- coding: utf-8 -*-
"""Assignment-12(2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y6rE7rrTTyxR6EXbkXYVR2H50MjPO0F2
"""

import numpy as np
import matplotlib.pyplot as plt

# calculate the probability of Both childrens are female and At least one children is female
Both_Child_female=(1/4)
Atleast_Child_female=(1/2)

#find probability P2:
P2=(Both_Child_female)/(Atleast_Child_female)

print("P2=")
print(P2)