# -*- coding: utf-8 -*-
"""Assignment-12(1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17lUaV_gXRwsuWR2NE8RxR4D17VY_jNR9
"""

import numpy as np
import matplotlib.pyplot as plt


# calculate the probability of Both childrens are male and At least one children is male
Both_Child_male=(1/4)
Atleast_Child_male=(3/4)

#find probability P1:
P1=(Both_Child_male)/(Atleast_Child_male)

print("P1=")
print(P1)
